# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 22, 1, 21, 423021), verbose_name='Время поступления'),
        ),
    ]
