# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование'),
        ),
    ]
