# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 1, 16, 54, 454620), verbose_name='Дата поступления'),
        ),
    ]
