# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='change_date',
            field=models.DateTimeField(null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(verbose_name='Кол.'),
        ),
    ]
