# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20161015_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstorage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='min_count',
            field=models.IntegerField(default=0, verbose_name='Минимальное количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductStorage',
        ),
    ]
