# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20161015_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_product', 'Просмотр товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
