# Generated by Django 2.2.10 on 2020-02-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200210_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_shipments', to='storage.Invoice', verbose_name='Приемка товара'),
        ),
    ]
