# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_productkind_min_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='overhead',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Накладные расходы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дисконт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_shop',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заведение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wholesale',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптом'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость'),
        ),
    ]
