# Generated by Django 2.2.10 on 2020-02-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20200212_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipments',
        ),
    ]
