# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 23:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0006_auto_20161027_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRevise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_revise', models.IntegerField(verbose_name='Количество по сверке')),
                ('count_storage', models.IntegerField(verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.Product', verbose_name='Товар для сверки')),
            ],
            options={
                'db_table': 'storage_product_revise',
                'verbose_name_plural': 'Товары для сверки',
                'verbose_name': 'Товар для сверки',
            },
        ),
        migrations.CreateModel(
            name='Revise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACCEPT', 'Принята')], default='DRAFT', max_length=7, verbose_name='Статус сверки')),
                ('revise_date', models.DateTimeField(verbose_name='Дата сверки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revises', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('products_revise', models.ManyToManyField(to='storage.ProductRevise', verbose_name='Товары для сверки')),
            ],
            options={
                'db_table': 'storage_revise',
                'verbose_name_plural': 'Сверки товаров',
                'verbose_name': 'Сверка товара',
                'permissions': [('import_revise', 'Сверка товара')],
            },
        ),
    ]
