# Generated by Django 2.2.10 on 2020-02-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_invoice_shipments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprovider',
            options={'ordering': ['provider_name'], 'verbose_name': 'Поставщик товара', 'verbose_name_plural': 'Поставщики товара'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='storage.Invoice', verbose_name='Приемка товара'),
        ),
    ]
