# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20161130_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ACCEPT', 'Принято')], default='ACCEPT', max_length=6, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
