# Generated by Django 2.2.10 on 2020-03-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20200212_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
