# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revise',
            options={'verbose_name': 'Сверка товара', 'verbose_name_plural': 'Сверки товаров'},
        ),
        migrations.AddField(
            model_name='productrevise',
            name='revise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.Revise', verbose_name='Сверка'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revises', to=settings.AUTH_USER_MODEL, verbose_name='Сверку совершил'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='products_revise',
            field=models.ManyToManyField(related_name='revises', to='storage.ProductRevise', verbose_name='Товары для сверки'),
        ),
    ]
