# Generated by Django 2.2.10 on 2020-05-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_product_price_discount'),
    ]

    operations = [
        migrations.RunSQL("UPDATE storage_product SET price_discount = price_retail")
    ]
