# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_revise_m2m_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revise',
            name='products_revise',
        ),
    ]
