# Generated by Django 2.2.10 on 2020-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20200507_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дисконт'),
        ),
    ]
