# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20170226_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Доступен в продаже'),
        ),
        migrations.AddField(
            model_name='productkind',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Доступен в продаже'),
        ),
    ]
