# Generated by Django 3.0.2 on 2020-02-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128, verbose_name='Тип покупателя')),
            ],
            options={
                'verbose_name': 'Тип покупателей',
                'verbose_name_plural': 'Тип покупателя',
                'db_table': 'market_customer_types',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Наименование')),
                ('main_contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ответственное лицо')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер телефона')),
                ('communication_links', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылки для связи')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Доп.информация')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.CustomerType', verbose_name='Тип покупателя')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатель',
                'db_table': 'market_customers',
            },
        ),
    ]
