# Generated by Django 2.2.10 on 2020-02-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Наименование покупателя'),
        ),
    ]
