# Generated by Django 2.2.10 on 2020-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200210_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Покупатели', 'verbose_name_plural': 'Покупатель'},
        ),
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['type_name'], 'verbose_name': 'Тип покупателей', 'verbose_name_plural': 'Тип покупателя'},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'customer_type'), name='unique_customer'),
        ),
    ]
