# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_auto_20160708_2215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Пластиковая карта'), ('CREDIT', 'Долг'), ('REVISE', 'Сверка')], max_length=18, unique=True, verbose_name='Тип кассы')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
            ],
            options={
                'db_table': 'cashbox_cashbox',
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
        migrations.CreateModel(
            name='CashTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_date', models.DateTimeField(db_index=True, verbose_name='Время вывода денег')),
                ('cash_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Пластиковая карта'), ('CREDIT', 'Долг'), ('REVISE', 'Сверка')], max_length=18, verbose_name='Тип кассы')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('description', models.CharField(max_length=300, verbose_name='Доп.информация')),
            ],
            options={
                'db_table': 'cashbox_cash_take',
                'verbose_name': 'Изьятие денег',
                'verbose_name_plural': 'Изьятие денег',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Пластиковая карта'), ('CREDIT', 'Долг'), ('REVISE', 'Сверка')], max_length=18, verbose_name='Тип оплаты')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Доп.информация')),
            ],
            options={
                'db_table': 'cashbox_payment_type',
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='ProductSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время продажи')),
                ('payments', models.ManyToManyField(to='cashbox.PaymentType', verbose_name='Оплата')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'db_table': 'cashbox_product_sell',
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='ProductShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('product_count', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Product', verbose_name='Товар')),
            ],
            options={
                'db_table': 'cashbox_shipment',
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданный товар',
            },
        ),
        migrations.AddField(
            model_name='productsell',
            name='shipments',
            field=models.ManyToManyField(to='cashbox.ProductShipment', verbose_name='Товары'),
        ),
    ]
