# Generated by Django 3.0.2 on 2020-02-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashBox',
        ),
        migrations.DeleteModel(
            name='CashTake',
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='cash_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Пластиковая карта'), ('CREDIT', 'Долг')], max_length=18, verbose_name='Тип оплаты'),
        ),
    ]
