# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_auto_20161027_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='productshipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.Product', verbose_name='Товар'),
        ),
    ]
