# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_auto_20161130_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='rebate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Скидка(%)'),
        ),
    ]
