# Generated by Django 3.0.2 on 2020-02-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial_create'),
        ('cashbox', '0004_productsell_def_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Customer', verbose_name='Покупатель'),
        ),
    ]
