# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0004_auto_20170115_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshipment',
            name='initial_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Первоначальная стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productshipment',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическая стоимость'),
        ),
    ]
