# Generated by Django 2.2.10 on 2020-02-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0005_auto_20200203_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshipment',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='has_shipments', to='cashbox.ProductSell', verbose_name='Продажа'),
        ),
    ]
