# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:41
from __future__ import unicode_literals

from django.db import migrations, models

from src.apps.cashbox.models import ProductShipment


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0005_auto_20170329_1721'),
    ]

    # Заполняем первоначальную себестоимость товара из товара ->
    # прибыль до даты обновления будет неверной, т.к раньше была завязка на себестоимость товара, которая постоянно изменялась...
    def fill_product_cost_price(apps, schema_editor):
        for shipment in ProductShipment.objects.select_related('product').all():
            shipment.product_cost_price = shipment.product.cost_price
            shipment.save()

    operations = [
        migrations.AddField(
            model_name='productshipment',
            name='product_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость товара при продаже'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_product_cost_price),
    ]
