# Generated by Django 2.2.10 on 2020-02-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0006_productshipment_sell'),
    ]

    operations = [
        migrations.RunSQL("UPDATE cashbox_shipment "
                          "SET sell_id = mm.productsell_id "
                          "FROM cashbox_product_sell_shipments mm "
                          "WHERE cashbox_shipment.id = mm.productshipment_id"),
    ]
