# Generated by Django 2.2.10 on 2020-02-10 23:39

from django.db import migrations


def save_sell_fk(apps, schema):
    Sell = apps.get_model('cashbox', 'ProductSell')
    ProductShipment = apps.get_model('cashbox', 'ProductShipment')

    for product_shipment in ProductShipment.objects.all():
        product_shipment.sell = product_shipment.productsell_set.all().first()
        product_shipment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0006_productshipment_sell'),
    ]

    operations = [
        migrations.RunPython(save_sell_fk),
    ]
