# Generated by Django 2.2.10 on 2020-02-11 00:09

from django.db import migrations


def remove_empty_shipments(apps, schema):
    ProductShipment = apps.get_model('cashbox', 'ProductShipment')
    ProductShipment.objects.filter(sell_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0007_auto_20200210_2339'),
    ]

    operations = [
        migrations.RunPython(remove_empty_shipments),
    ]
