# Generated by Django 2.2.10 on 2020-02-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0007_auto_20200210_2339'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM cashbox_shipment WHERE sell_id IS NULL"),
    ]
