# Generated by Django 2.2.10 on 2020-02-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0008_auto_20200211_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsell',
            name='shipments',
        ),
        migrations.AlterField(
            model_name='productshipment',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='cashbox.ProductSell', verbose_name='Продажа'),
        ),
    ]
