# Generated by Django 2.2.10 on 2020-02-11 00:21

from django.db import migrations


def save_sell_fk(apps, schema):
    Sell = apps.get_model('cashbox', 'ProductSell')
    PaymentType = apps.get_model('cashbox', 'PaymentType')

    for payment in PaymentType.objects.all():
        payment.sell = payment.productsell_set.all().first()
        payment.save()

    PaymentType.objects.filter(sell_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0010_paymenttype_sell'),
    ]

    operations = [
        migrations.RunPython(save_sell_fk),
    ]
