# Generated by Django 2.2.10 on 2020-02-11 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0011_auto_20200211_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsell',
            name='payments',
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashbox.ProductSell', verbose_name='Продажа'),
        ),
    ]
