# Generated by Django 3.0.2 on 2020-02-02 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='ext_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_work_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='ext_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
